#!/bin/sh

VERSION="$1"
mvn versions:set -DnewVersion="$VERSION" -DprocessAllModules -f backend/pom.xml
cd frontend && npm version "$VERSION" && cd ..
cd integration-tests && npm version "$VERSION" && cd ..